(deftheme my-flatline
  "Created 2020-09-23.")

(custom-theme-set-faces
 'my-flatline
 '(cursor ((t (:foreground "#f8f8f8" :background "#bbbcbd"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:foundry "outline" :family "Arial")) (t (:family "Sans Serif"))))
 '(escape-glyph ((t (:weight bold :foreground "#f6f080"))))
 '(homoglyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#f6f080"))))
 '(highlight ((t (:background "#202325"))))
 '(region ((t (:background "#3c3f42"))))
 '(shadow ((((class color grayscale) (min-colors 88) (background light)) (:foreground "grey50")) (((class color grayscale) (min-colors 88) (background dark)) (:foreground "grey70")) (((class color) (min-colors 8) (background light)) (:foreground "green")) (((class color) (min-colors 8) (background dark)) (:foreground "yellow"))))
 '(secondary-selection ((t (:background "#2e3235"))))
 '(trailing-whitespace ((t (:background "#ff4a52"))))
 '(font-lock-builtin-face ((t (:weight bold :foreground "#fa9a4b"))))
 '(font-lock-comment-delimiter-face ((t (:foreground "#798188"))))
 '(font-lock-comment-face ((t (:foreground "#798188"))))
 '(font-lock-constant-face ((t (:foreground "#b9d977"))))
 '(font-lock-doc-face ((t (:foreground "#798188"))))
 '(font-lock-function-name-face ((t (:foreground "#72aaca" :weight bold))))
 '(font-lock-keyword-face ((t (:foreground "#fa9a4b" :weight bold))))
 '(font-lock-negation-char-face ((t (:foreground "#f6f080"))))
 '(font-lock-preprocessor-face ((t (:foreground "#cfe2f2"))))
 '(font-lock-regexp-grouping-backslash ((t (:weight bold :foreground "#40b83e"))))
 '(font-lock-regexp-grouping-construct ((t (:weight bold :foreground "#f6f080"))))
 '(font-lock-string-face ((t (:foreground "#cfe2f2"))))
 '(font-lock-type-face ((t (:foreground "#72aaca"))))
 '(font-lock-variable-name-face ((t (:foreground "#f6f080"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#f1e94b"))))
 '(button ((t (:underline (:color foreground-color :style line)))))
 '(link ((t (:foreground "#f6f080" :underline t))))
 '(link-visited ((t (:weight normal :underline (:color foreground-color :style line) :foreground "#f1e94b"))))
 '(fringe ((t (:foreground "#f8f8f8" :background "#2e303a"))))
 '(header-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#f6f080" :background "#1f2124"))))
 '(tooltip ((t (:foreground "black" :background "lightyellow" :inherit (variable-pitch)))))
 '(mode-line ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#b6d877" :background "#1f2124"))))
 '(mode-line-inactive ((t (:box (:line-width -1 :color nil :style released-button) :foreground "#41a83e" :background "#202325"))))
 '(isearch ((t (:background "#1f2124" :foreground "#f1e94b" :inverse-video t :weight bold))))
 '(isearch-fail ((t (:foreground "#f8f8f8" :background "#c92b14"))))
 '(lazy-highlight ((t nil)))
 '(match ((t (:weight bold :foreground "#f6aa11" :background "#1f2124"))))
 '(next-error ((t (:inherit (region)))))
  '(query-replace ((t (:inherit (isearch)))))
  ;; flatlines defaults, I changed to "light gray"
  '(default ((t (:inherit nil :stipple nil :background "#26292c" :foreground "light gray" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "PfEd" :family "DejaVu Sans Mono")))))
  ;; mistereo background is background "#2d3743" :foreground "#e1e1e0"
  ;;'(default ((t (:inherit nil :stipple nil :background "#26292c" :foreground "#e1e1e0" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 120 :width normal :foundry "PfEd" :family "DejaVu Sans Mono")))))

  
(provide-theme 'my-flatline)
